version: '3.9'
services:
  api:
    container_name: rate-limiter-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    environment:
      - PORT=4000
      - REDIS_CONNECTION_STRING=redis://db-redis:6379
    volumes:
      - ./:/usr/src/app
    networks:
      - ratelimiternet

  db-redis:
    image: redis:alpine
    ports:
      - 6379:6379
    networks:
      - ratelimiternet

networks:
  ratelimiternet: